Epoch:   0%|                                                                                                                        | 0/100 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/workdir/Speaker_Verification_version_1.0/Speaker-Verification/issai_task_3_train.py", line 220, in <module>
    model = train_model(model,
  File "/workdir/Speaker_Verification_version_1.0/Speaker-Verification/speaker_verification/train.py", line 42, in train_model
    model, train_loss, train_acc = train_singe_epoch(model,
  File "/workdir/Speaker_Verification_version_1.0/Speaker-Verification/speaker_verification/train.py", line 118, in train_singe_epoch
    for batch in pbar:
  File "/usr/local/lib/python3.8/dist-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/dataloader.py", line 628, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/dataloader.py", line 1333, in _next_data
    return self._process_data(data)
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/dataloader.py", line 1359, in _process_data
    data.reraise()
  File "/usr/local/lib/python3.8/dist-packages/torch/_utils.py", line 543, in reraise
    raise exception
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/_utils/fetch.py", line 58, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/_utils/fetch.py", line 58, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/workdir/Speaker_Verification_version_1.0/Speaker-Verification/speaker_verification/dataset.py", line 39, in __getitem__
    sample = self._get_data(index)
  File "/workdir/Speaker_Verification_version_1.0/Speaker-Verification/speaker_verification/dataset.py", line 53, in _get_data
    data_wav = self.audio_transform(data_wav, sample_rate)
  File "/workdir/Speaker_Verification_version_1.0/Speaker-Verification/speaker_verification/transforms.py", line 93, in transform
    signal = signal[:,left_edge:right_edge]
TypeError: slice indices must be integers or None or have an __index__ method